//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMICISite.wcfServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuariosVM", Namespace="http://schemas.datacontract.org/2004/07/wcfMinIndustria.Model")]
    [System.SerializableAttribute()]
    public partial class UsuariosVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BachesVM", Namespace="http://schemas.datacontract.org/2004/07/wcfMinIndustria.Model")]
    [System.SerializableAttribute()]
    public partial class BachesVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FcreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBacheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TamanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fcreacion {
            get {
                return this.FcreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FcreacionField, value) != true)) {
                    this.FcreacionField = value;
                    this.RaisePropertyChanged("Fcreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBache {
            get {
                return this.IdBacheField;
            }
            set {
                if ((this.IdBacheField.Equals(value) != true)) {
                    this.IdBacheField = value;
                    this.RaisePropertyChanged("IdBache");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicionField, value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioridadField, value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tamano {
            get {
                return this.TamanoField;
            }
            set {
                if ((object.ReferenceEquals(this.TamanoField, value) != true)) {
                    this.TamanoField = value;
                    this.RaisePropertyChanged("Tamano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanoVM", Namespace="http://schemas.datacontract.org/2004/07/wcfMinIndustria.Model")]
    [System.SerializableAttribute()]
    public partial class DanoVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoReparacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FcreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBacheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CostoReparacion {
            get {
                return this.CostoReparacionField;
            }
            set {
                if ((this.CostoReparacionField.Equals(value) != true)) {
                    this.CostoReparacionField = value;
                    this.RaisePropertyChanged("CostoReparacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fcreacion {
            get {
                return this.FcreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FcreacionField, value) != true)) {
                    this.FcreacionField = value;
                    this.RaisePropertyChanged("Fcreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBache {
            get {
                return this.IdBacheField;
            }
            set {
                if ((this.IdBacheField.Equals(value) != true)) {
                    this.IdBacheField = value;
                    this.RaisePropertyChanged("IdBache");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReporte {
            get {
                return this.IdReporteField;
            }
            set {
                if ((this.IdReporteField.Equals(value) != true)) {
                    this.IdReporteField = value;
                    this.RaisePropertyChanged("IdReporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDano {
            get {
                return this.TipoDanoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDanoField, value) != true)) {
                    this.TipoDanoField = value;
                    this.RaisePropertyChanged("TipoDano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformeVM", Namespace="http://schemas.datacontract.org/2004/07/wcfMinIndustria.Model")]
    [System.SerializableAttribute()]
    public partial class InformeVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrigadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CantRellenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoBacheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoBacheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorasDeReparacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBacheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInformeBacheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TamanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brigada {
            get {
                return this.BrigadaField;
            }
            set {
                if ((object.ReferenceEquals(this.BrigadaField, value) != true)) {
                    this.BrigadaField = value;
                    this.RaisePropertyChanged("Brigada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CantRelleno {
            get {
                return this.CantRellenoField;
            }
            set {
                if ((object.ReferenceEquals(this.CantRellenoField, value) != true)) {
                    this.CantRellenoField = value;
                    this.RaisePropertyChanged("CantRelleno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CostoBache {
            get {
                return this.CostoBacheField;
            }
            set {
                if ((this.CostoBacheField.Equals(value) != true)) {
                    this.CostoBacheField = value;
                    this.RaisePropertyChanged("CostoBache");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipamiento {
            get {
                return this.EquipamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipamientoField, value) != true)) {
                    this.EquipamientoField = value;
                    this.RaisePropertyChanged("Equipamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoBache {
            get {
                return this.EstadoBacheField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoBacheField, value) != true)) {
                    this.EstadoBacheField = value;
                    this.RaisePropertyChanged("EstadoBache");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HorasDeReparacion {
            get {
                return this.HorasDeReparacionField;
            }
            set {
                if ((object.ReferenceEquals(this.HorasDeReparacionField, value) != true)) {
                    this.HorasDeReparacionField = value;
                    this.RaisePropertyChanged("HorasDeReparacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBache {
            get {
                return this.IdBacheField;
            }
            set {
                if ((this.IdBacheField.Equals(value) != true)) {
                    this.IdBacheField = value;
                    this.RaisePropertyChanged("IdBache");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInformeBache {
            get {
                return this.IdInformeBacheField;
            }
            set {
                if ((this.IdInformeBacheField.Equals(value) != true)) {
                    this.IdInformeBacheField = value;
                    this.RaisePropertyChanged("IdInformeBache");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tamano {
            get {
                return this.TamanoField;
            }
            set {
                if ((this.TamanoField.Equals(value) != true)) {
                    this.TamanoField = value;
                    this.RaisePropertyChanged("Tamano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/wcfMinIndustria")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RespuestaOkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRespuesta {
            get {
                return this.IdRespuestaField;
            }
            set {
                if ((this.IdRespuestaField.Equals(value) != true)) {
                    this.IdRespuestaField = value;
                    this.RaisePropertyChanged("IdRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSolicitud {
            get {
                return this.IdSolicitudField;
            }
            set {
                if ((this.IdSolicitudField.Equals(value) != true)) {
                    this.IdSolicitudField = value;
                    this.RaisePropertyChanged("IdSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RespuestaOk {
            get {
                return this.RespuestaOkField;
            }
            set {
                if ((this.RespuestaOkField.Equals(value) != true)) {
                    this.RespuestaOkField = value;
                    this.RaisePropertyChanged("RespuestaOk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfServicio.IwcfExtService")]
    public interface IwcfExtService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Login", ReplyAction="http://tempuri.org/IwcfExtService/LoginResponse")]
        SMICISite.wcfServicio.UsuariosVM Login(string strUsuario, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Login", ReplyAction="http://tempuri.org/IwcfExtService/LoginResponse")]
        System.Threading.Tasks.Task<SMICISite.wcfServicio.UsuariosVM> LoginAsync(string strUsuario, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Listado", ReplyAction="http://tempuri.org/IwcfExtService/ListadoResponse")]
        System.Collections.Generic.List<SMICISite.wcfServicio.BachesVM> Listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Listado", ReplyAction="http://tempuri.org/IwcfExtService/ListadoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SMICISite.wcfServicio.BachesVM>> ListadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/ListadoDano", ReplyAction="http://tempuri.org/IwcfExtService/ListadoDanoResponse")]
        System.Collections.Generic.List<SMICISite.wcfServicio.DanoVM> ListadoDano();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/ListadoDano", ReplyAction="http://tempuri.org/IwcfExtService/ListadoDanoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SMICISite.wcfServicio.DanoVM>> ListadoDanoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/ListadoInforme", ReplyAction="http://tempuri.org/IwcfExtService/ListadoInformeResponse")]
        System.Collections.Generic.List<SMICISite.wcfServicio.InformeVM> ListadoInforme();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/ListadoInforme", ReplyAction="http://tempuri.org/IwcfExtService/ListadoInformeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SMICISite.wcfServicio.InformeVM>> ListadoInformeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/RegistroReporteBache", ReplyAction="http://tempuri.org/IwcfExtService/RegistroReporteBacheResponse")]
        SMICISite.wcfServicio.Respuesta RegistroReporteBache(SMICISite.wcfServicio.BachesVM objRegistroBaches);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/RegistroReporteBache", ReplyAction="http://tempuri.org/IwcfExtService/RegistroReporteBacheResponse")]
        System.Threading.Tasks.Task<SMICISite.wcfServicio.Respuesta> RegistroReporteBacheAsync(SMICISite.wcfServicio.BachesVM objRegistroBaches);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/RegistroReporteDano", ReplyAction="http://tempuri.org/IwcfExtService/RegistroReporteDanoResponse")]
        SMICISite.wcfServicio.Respuesta RegistroReporteDano(SMICISite.wcfServicio.DanoVM objRegistroDano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/RegistroReporteDano", ReplyAction="http://tempuri.org/IwcfExtService/RegistroReporteDanoResponse")]
        System.Threading.Tasks.Task<SMICISite.wcfServicio.Respuesta> RegistroReporteDanoAsync(SMICISite.wcfServicio.DanoVM objRegistroDano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/RegistroInforme", ReplyAction="http://tempuri.org/IwcfExtService/RegistroInformeResponse")]
        SMICISite.wcfServicio.Respuesta RegistroInforme(SMICISite.wcfServicio.InformeVM objRegistroInforme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/RegistroInforme", ReplyAction="http://tempuri.org/IwcfExtService/RegistroInformeResponse")]
        System.Threading.Tasks.Task<SMICISite.wcfServicio.Respuesta> RegistroInformeAsync(SMICISite.wcfServicio.InformeVM objRegistroInforme);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwcfExtServiceChannel : SMICISite.wcfServicio.IwcfExtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwcfExtServiceClient : System.ServiceModel.ClientBase<SMICISite.wcfServicio.IwcfExtService>, SMICISite.wcfServicio.IwcfExtService {
        
        public IwcfExtServiceClient() {
        }
        
        public IwcfExtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwcfExtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfExtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfExtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SMICISite.wcfServicio.UsuariosVM Login(string strUsuario, string strPass) {
            return base.Channel.Login(strUsuario, strPass);
        }
        
        public System.Threading.Tasks.Task<SMICISite.wcfServicio.UsuariosVM> LoginAsync(string strUsuario, string strPass) {
            return base.Channel.LoginAsync(strUsuario, strPass);
        }
        
        public System.Collections.Generic.List<SMICISite.wcfServicio.BachesVM> Listado() {
            return base.Channel.Listado();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SMICISite.wcfServicio.BachesVM>> ListadoAsync() {
            return base.Channel.ListadoAsync();
        }
        
        public System.Collections.Generic.List<SMICISite.wcfServicio.DanoVM> ListadoDano() {
            return base.Channel.ListadoDano();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SMICISite.wcfServicio.DanoVM>> ListadoDanoAsync() {
            return base.Channel.ListadoDanoAsync();
        }
        
        public System.Collections.Generic.List<SMICISite.wcfServicio.InformeVM> ListadoInforme() {
            return base.Channel.ListadoInforme();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SMICISite.wcfServicio.InformeVM>> ListadoInformeAsync() {
            return base.Channel.ListadoInformeAsync();
        }
        
        public SMICISite.wcfServicio.Respuesta RegistroReporteBache(SMICISite.wcfServicio.BachesVM objRegistroBaches) {
            return base.Channel.RegistroReporteBache(objRegistroBaches);
        }
        
        public System.Threading.Tasks.Task<SMICISite.wcfServicio.Respuesta> RegistroReporteBacheAsync(SMICISite.wcfServicio.BachesVM objRegistroBaches) {
            return base.Channel.RegistroReporteBacheAsync(objRegistroBaches);
        }
        
        public SMICISite.wcfServicio.Respuesta RegistroReporteDano(SMICISite.wcfServicio.DanoVM objRegistroDano) {
            return base.Channel.RegistroReporteDano(objRegistroDano);
        }
        
        public System.Threading.Tasks.Task<SMICISite.wcfServicio.Respuesta> RegistroReporteDanoAsync(SMICISite.wcfServicio.DanoVM objRegistroDano) {
            return base.Channel.RegistroReporteDanoAsync(objRegistroDano);
        }
        
        public SMICISite.wcfServicio.Respuesta RegistroInforme(SMICISite.wcfServicio.InformeVM objRegistroInforme) {
            return base.Channel.RegistroInforme(objRegistroInforme);
        }
        
        public System.Threading.Tasks.Task<SMICISite.wcfServicio.Respuesta> RegistroInformeAsync(SMICISite.wcfServicio.InformeVM objRegistroInforme) {
            return base.Channel.RegistroInformeAsync(objRegistroInforme);
        }
    }
}
