//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMICISite.wcfServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfServicio.IwcfExtService")]
    public interface IwcfExtService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/DoWork", ReplyAction="http://tempuri.org/IwcfExtService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/DoWork", ReplyAction="http://tempuri.org/IwcfExtService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Login", ReplyAction="http://tempuri.org/IwcfExtService/LoginResponse")]
        int Login(string strUsuario, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Login", ReplyAction="http://tempuri.org/IwcfExtService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string strUsuario, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Registro", ReplyAction="http://tempuri.org/IwcfExtService/RegistroResponse")]
        int Registro(string strUsuario, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Registro", ReplyAction="http://tempuri.org/IwcfExtService/RegistroResponse")]
        System.Threading.Tasks.Task<int> RegistroAsync(string strUsuario, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/NuevaSolicitud", ReplyAction="http://tempuri.org/IwcfExtService/NuevaSolicitudResponse")]
        int NuevaSolicitud();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/NuevaSolicitud", ReplyAction="http://tempuri.org/IwcfExtService/NuevaSolicitudResponse")]
        System.Threading.Tasks.Task<int> NuevaSolicitudAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/DetalleSolicitud", ReplyAction="http://tempuri.org/IwcfExtService/DetalleSolicitudResponse")]
        int DetalleSolicitud();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/DetalleSolicitud", ReplyAction="http://tempuri.org/IwcfExtService/DetalleSolicitudResponse")]
        System.Threading.Tasks.Task<int> DetalleSolicitudAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Solicitudes", ReplyAction="http://tempuri.org/IwcfExtService/SolicitudesResponse")]
        int Solicitudes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfExtService/Solicitudes", ReplyAction="http://tempuri.org/IwcfExtService/SolicitudesResponse")]
        System.Threading.Tasks.Task<int> SolicitudesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwcfExtServiceChannel : SMICISite.wcfServicio.IwcfExtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwcfExtServiceClient : System.ServiceModel.ClientBase<SMICISite.wcfServicio.IwcfExtService>, SMICISite.wcfServicio.IwcfExtService {
        
        public IwcfExtServiceClient() {
        }
        
        public IwcfExtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwcfExtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfExtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfExtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int Login(string strUsuario, string strPass) {
            return base.Channel.Login(strUsuario, strPass);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string strUsuario, string strPass) {
            return base.Channel.LoginAsync(strUsuario, strPass);
        }
        
        public int Registro(string strUsuario, string strPass) {
            return base.Channel.Registro(strUsuario, strPass);
        }
        
        public System.Threading.Tasks.Task<int> RegistroAsync(string strUsuario, string strPass) {
            return base.Channel.RegistroAsync(strUsuario, strPass);
        }
        
        public int NuevaSolicitud() {
            return base.Channel.NuevaSolicitud();
        }
        
        public System.Threading.Tasks.Task<int> NuevaSolicitudAsync() {
            return base.Channel.NuevaSolicitudAsync();
        }
        
        public int DetalleSolicitud() {
            return base.Channel.DetalleSolicitud();
        }
        
        public System.Threading.Tasks.Task<int> DetalleSolicitudAsync() {
            return base.Channel.DetalleSolicitudAsync();
        }
        
        public int Solicitudes() {
            return base.Channel.Solicitudes();
        }
        
        public System.Threading.Tasks.Task<int> SolicitudesAsync() {
            return base.Channel.SolicitudesAsync();
        }
    }
}
