//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfMinIndustria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeBache
    {
        public int IdBache { get; set; }
        public string Ubicacion { get; set; }
        public double Tamano { get; set; }
        public string Brigada { get; set; }
        public string Equipamiento { get; set; }
        public string HorasDeReparacion { get; set; }
        public string EstadoBache { get; set; }
        public string CantRelleno { get; set; }
        public double CostoBache { get; set; }
    
        public virtual Baches Baches { get; set; }
    }
}
