//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfMinIndustria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteDano
    {
        public int IdReporte { get; set; }
        public string TipoDano { get; set; }
        public double CostoReparacion { get; set; }
        public string IdUsuario { get; set; }
        public int IdBache { get; set; }
    
        public virtual Baches Baches { get; set; }
    }
}
