//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfMinIndustria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosMICI
    {
        public int IdUsuarioMICI { get; set; }
        public string NombreCompleto { get; set; }
        public string Email { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FCreacion { get; set; }
    }
}
